# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(help_text='The id, probaly an auto-inc integer.', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Board or Commission',
                'verbose_name_plural': 'Boards and Commissions',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(help_text='Document/video, etc. scraped from the css class', max_length=50)),
                ('date', models.DateField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('dirty', models.BooleanField(default=False)),
                ('scrape_status', models.CharField(choices=[('scraped', 'Scraped'), ('toscrape', 'To Scrape'), ('error', 'Error Scraping')], default='no', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, help_text='The text scraped from the pdf', null=True)),
                ('url', models.URLField()),
                ('bandc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.BandC')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bandc',
            name='years_active',
            field=models.ManyToManyField(to='agenda.Year'),
        ),
    ]
