# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandc',
            options={'ordering': ('name',), 'verbose_name': 'Board or Commission', 'verbose_name_plural': 'Boards and Commissions'},
        ),
        migrations.AddField(
            model_name='bandc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bandc',
            name='homepage',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bandc',
            name='slug',
            field=models.SlugField(default='slug', max_length=255),
            preserve_default=False,
        ),
    ]
