# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandc',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
