# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandc",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="The id, probaly an auto-inc integer.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
