# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20160117_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandc',
            name='scrapable',
            field=models.BooleanField(default=True),
        ),
    ]
