# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_bandc_scrapable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(help_text='Document/video, etc. scraped from the css class', max_length=50)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('dirty', models.BooleanField(default=False)),
                ('scrape_status', models.CharField(choices=[('scraped', 'Scraped'), ('toscrape', 'To Scrape'), ('error', 'Error Scraping')], default='no', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, help_text='The text scraped from the pdf', null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='bandc',
        ),
        migrations.AddField(
            model_name='bandc',
            name='scraped_at',
            field=models.DateTimeField(blank=True, help_text='The last time documents were scraped.', null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='meeting',
            name='bandc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.BandC'),
        ),
        migrations.AddField(
            model_name='document',
            name='bandc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.BandC'),
        ),
        migrations.AddField(
            model_name='document',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Meeting'),
        ),
    ]
