# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20160118_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='bandc',
        ),
        migrations.RemoveField(
            model_name='document',
            name='dirty',
        ),
        migrations.AddField(
            model_name='meeting',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 18, 3, 55, 56, 601566, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='scrape_status',
            field=models.CharField(choices=[('scraped', 'Scraped'), ('toscrape', 'To Scrape'), ('error', 'Error Scraping')], default='scraped', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='bandc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='agenda.BandC'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
