# Generated by Django 3.0.2 on 2020-01-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0005_document_page_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="edims_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Documents from cancelled meetings become inactive",
            ),
        ),
    ]
