# Generated by Django 3.0.2 on 2020-01-26 00:09

from django.db import migrations


def backfill_edims_id(apps, schema_editor):
    Document = apps.get_model("agenda", "Document")
    for doc in Document.objects.filter(edims_id=None):
        if "/edims/document.cfm" in doc.url:
            doc.edims_id = doc.url.rsplit("=", 2)[-1]
            doc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0006_add_edims_id"),
    ]

    operations = [migrations.RunPython(backfill_edims_id)]
