# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_document_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-meeting__date',)},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='bandc',
            name='years_active',
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, help_text='The text extracted from the pdf', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
