# Generated by Django 3.0.2 on 2020-03-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_backfill_edims_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('num_documents_found', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, help_text='Errors that occured while scraping', null=True)),
                ('bandcs_scraped', models.ManyToManyField(to='agenda.BandC')),
                ('documents_scraped', models.ManyToManyField(to='agenda.Document')),
            ],
        ),
    ]
