# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20160118_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandc',
            name='identifier',
            field=models.CharField(help_text='The id, probaly an auto-inc integer.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agenda.Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set([('date', 'bandc')]),
        ),
    ]
