# Generated by Django 4.0.10 on 2025-03-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0008_scrapelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapelog",
            name="duration",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How long the scrape took (in milliseconds)",
                null=True,
            ),
        ),
    ]
