# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20160118_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scrape_status',
            field=models.CharField(choices=[('toscrape', 'To Scrape'), ('scraped', 'Scraped'), ('error', 'Error Scraping')], default='toscrape', max_length=20),
        ),
    ]
