# Generated by Django 6.0.1 on 2026-01-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0009_alter_scrapelog_duration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["active", "scraped_at"], name="agenda_docu_active_6df265_idx"
            ),
        ),
    ]
