# Generated by Django 6.0.1 on 2026-02-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0010_document_agenda_docu_active_6df265_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandc",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the city lists this board as active. Set by --init-list.",
            ),
        ),
    ]
