dist: xenial
language: python
python: "3.8"
cache:
  - pip
before_install: "pip install poetry"
install: "make install"
script: "make test"
branches:
  only:
    - master
notifications:
  email: false
