TABLE = 'bandc_items'

# CONFIGURATION

PAGES = (
    # bandc_slug: http://www.austintexas.gov/<bandc_slug> (sometimes)
    # id: http://www.austintexas.gov/cityclerk/boards_commissions/meetings/
    #     <year>_<id>_<page>.htm
    # name
    ('aaac', '7', 'Austin Airport Advisory Commission'),
    ('aac', '4', 'Animal Advisory Commission'),
    ('aachpc', '8', 'Austin Area Comprehensive HIV Planning Council'),
    ('aarac', '3', 'African American Resource Advisory Commission'),
    # ('abag', '73', 'Airport Boulevard Advisory Group'),  # last met in 2012
    ('amcpd', '11', u'Austin Mayor\u2019s Committee for People with Disabilities'),
    # ('applicant-review-panel', '114', 'Applicant Review Panel'),  # 2013
    ('artcomm', '5', 'Arts Commission'),
    ('asian-american-quality-life-advisory-commission-2', '123', 'Asian American Quality of Life Advisory Commission'),
    ('atceab', '13', 'Austin-Travis County EMS Advisory Board'),
    # ('atcicbt', '14', 'Austin Travis County Integral Care Board of Trustees'),
    ('austin-energy-low-income-customer-advocates', '127', 'Austin Energy Low Income Customer Advocates'),
    ('austin-generation-resource-planning-task-force', '128', 'Austin Generation Resource Planning Task Force'),
    ('austin-water-resource-planning-task-force', '129', 'Austin Water Resource Planning Task Force'),
    ('bfcba', '16', 'Building and Fire Code Board of Appeals'),
    ('boa', '15', 'Board of Adjustment'),
    ('boards-and-commissions-transition-taskforce', '125', 'Boards and Commissions Transition Taskforce'),
    ('bondoversight', '2', 'Bond Oversight Committee'),
    ('bsc', '17', 'Building and Standards Commission'),
    ('cac', '21', 'Construction Advisory Committee'),
    ('cdc', '20', 'Community Development Commission'),
    # ('central-health-board-managers', 'None', 'Central Health Board of Managers'),
    ('city-austin-firefighters-police-officers-and-emergency-medical-services-personnel-civil-service-commission', '115', "City of Austin Firefighters', Police Officers' and Emergency Medical Services Personnel Civil Service Commission"),
    ('coia', '19', 'Commission on Immigrant Affairs'),
    ('commission-seniors', '120', 'Commission on Seniors'),
    ('commission-veterans-affairs', '112', 'Commission on Veterans Affairs'),
    ('commissionforwomen', '18', 'Commission for Women'),
    # ('cpcatf', '57', 'Comprehensive Plan Citizens Advisory Task Force'),
    ('cttc', '10', 'Austin Community Technology and Telecommunications Commission'),
    ('daccac', '23', 'Downtown Austin Community Court Advisory Committee'),
    ('designcommission', '22', 'Design Commission'),
    ('downtowncommission', '24', 'Downtown Commission'),
    ('ecc', '25', 'Early Childhood Council'),
    ('electricboard', '26', 'Electric Board'),
    ('envboard', '28', 'Environmental Board'),
    ('erc', '29', 'Ethics Review Commission'),
    ('euc', '27', 'Electric Utility Commission'),
    ('haca', '32', 'Housing Authority'),
    ('hispaniclatino-quality-life-resource-advisory-commission', '119', 'Hispanic/Latino Quality of Life Resource Advisory Commission'),
    ('hlc', '31', 'Historic Landmark Commission'),
    ('hrc', '33', 'Human Rights Commission'),
    # ('ifac', '34', 'Impact Fee Advisory Committee'),
    ('independent-citizens-redistricting-commission', '116', 'Independent Citizens Redistricting Commission'),
    ('land-development-code-advisory-group', '111', 'Land Development Code Advisory Group'),
    # ('latf', '99', 'Lake Austin Task Force'),
    ('librarycommission', '35', 'Library Commission'),
    ('maccab', '38', 'Mexican American Cultural Center Advisory Board'),
    ('mbewbe', '36', 'MBEWBE/Small Business Enterprise Procurement Program Advisory Committee'),
    ('mpsb', '37', 'Mechanical, Plumbing and Solar Board'),
    ('municipal-civil-service-commission', '113', 'Municipal Civil Service Commission'),
    ('musiccomm', '12', 'Austin Music Commission'),
    ('parb', '39', 'Parks and Recreation Board'),
    ('planningcommission', '40', 'Planning Commission'),
    ('psc', '41', 'Public Safety Commission'),
    ('rdcc', '43', 'Residential Design and Compatibility Commission'),
    ('rmc', '44', 'Resource Management Commission'),
    ('rmmapiac', '45', 'Robert Mueller Municipal Airport Plan Implementation Advisory Commission'),
    ('sfpb', '47', 'Sustainable Food Policy Board'),
    ('srb', '55', 'Sign Review Board'),
    # ('travis-central-appraisal-district-board-directors', 'None', 'Travis Central Appraisal District Board of Directors'),
    ('ufb', '48', 'Urban Forestry Board'),
    ('urbanrenewal', '49', 'Urban Renewal Board'),
    ('utc', '50', 'Urban Transportation Commission'),
    ('wpab', '53', 'Waterfront Planning Advisory Board'),
    ('wwc', '52', 'Water and Wastewater Commission'),
    ('zpc', '54', 'Zoning and Planning Commission'),
    ('zwac', '97', 'Zero Waste Advisory Commission'),
)
