.PHONY: samples
samples:
	mkdir -p $@
	curl https://www.austintexas.gov/cityclerk/boards_commissions/meetings/2014_12_1.htm > $@/music.html
	curl https://www.austintexas.gov/cityclerk/boards_commissions/meetings/2014_39_1.htm > $@/parks.html
	curl https://www.austintexas.gov/cityclerk/boards_commissions/meetings/2014_39_2.htm > $@/parks2.html
	curl https://www.austintexas.gov/cityclerk/boards_commissions/meetings/2016_134_1.htm > $@/2016_134_1.html
