name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # https://github.com/astral-sh/setup-uv/releases
      - uses: astral-sh/setup-uv@v9.0.0
      - uses: actions/setup-python@v7.0.0
        with:
          python-version-file: ".python-version"
      - run: uv sync --group dev
      - run: uv run make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: docker build --target test -t crccheck/atx-bandc:test .
      - run: make docker/test
